services:
  db:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: example
      POSTGRES_DB: tpa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: my_adminer
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - db

  api:
    image: maven:3.9-eclipse-temurin-25
    working_dir: /app
    volumes:
      - ./api:/app
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - db

  client:
    image: node:22
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    command: sh -c "npm ci && npm start -- --host 0.0.0.0 --poll 1000"
    ports:
      - "4200:4200"
    depends_on:
      - api

volumes:
  postgres_data:
