spring.application.name=api

spring.datasource.url=jdbc:postgresql://db:5432/tpa
spring.datasource.username=pguser
spring.datasource.password=example

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

server.port=8080


logging.level.org.hibernate.orm.boot=DEBUG

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json

jwt.secret=verySecretSecretKeyPlaceholder123416687324234234324234
jwt.expiration=2400