spring.application.name=api

spring.datasource.url=jdbc:postgresql://db:5432/tpa
spring.datasource.username=pguser
spring.datasource.password=example

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

logging.level.org.hibernate.orm.boot=DEBUG