/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for AssignmentController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, AssignmentViewOutput, AssignmentViewInput, AssignmentViewPatchInput } from "../models";

@Injectable({ providedIn: "root" })
export class AssignmentControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAll1(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<AssignmentViewOutput>>;
    getAll1(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<AssignmentViewOutput>>>;
    getAll1(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<AssignmentViewOutput>>>;
    getAll1(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/assignments`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createAssignment(assignmentViewInput: AssignmentViewInput, observe?: 'body', options?: RequestOptions<'json'>): Observable<AssignmentViewOutput>;
    createAssignment(assignmentViewInput: AssignmentViewInput, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AssignmentViewOutput>>;
    createAssignment(assignmentViewInput: AssignmentViewInput, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AssignmentViewOutput>>;
    createAssignment(assignmentViewInput: AssignmentViewInput, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/assignments`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: assignmentViewInput,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    patchAssignment(id: string, assignmentViewPatchInput: AssignmentViewPatchInput, observe?: 'body', options?: RequestOptions<'json'>): Observable<AssignmentViewOutput>;
    patchAssignment(id: string, assignmentViewPatchInput: AssignmentViewPatchInput, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AssignmentViewOutput>>;
    patchAssignment(id: string, assignmentViewPatchInput: AssignmentViewPatchInput, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AssignmentViewOutput>>;
    patchAssignment(id: string, assignmentViewPatchInput: AssignmentViewPatchInput, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/assignments/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: assignmentViewPatchInput,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteById(id: string, observe?: 'body', options?: RequestOptions<'text'>): Observable<string>;
    deleteById(id: string, observe?: 'response', options?: RequestOptions<'text'>): Observable<HttpResponse<string>>;
    deleteById(id: string, observe?: 'events', options?: RequestOptions<'text'>): Observable<HttpEvent<string>>;
    deleteById(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/assignments/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            responseType: 'text',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
