/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for EmployeeController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, EmployeeViewOutput, EmployeeViewInput, EmployeeViewPatchInput } from "../models";

@Injectable({ providedIn: "root" })
export class EmployeeControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAll(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<EmployeeViewOutput>>;
    getAll(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<EmployeeViewOutput>>>;
    getAll(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<EmployeeViewOutput>>>;
    getAll(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/employee`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createEmployee(employeeViewInput: EmployeeViewInput, observe?: 'body', options?: RequestOptions<'json'>): Observable<EmployeeViewOutput>;
    createEmployee(employeeViewInput: EmployeeViewInput, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<EmployeeViewOutput>>;
    createEmployee(employeeViewInput: EmployeeViewInput, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<EmployeeViewOutput>>;
    createEmployee(employeeViewInput: EmployeeViewInput, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/employee`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: employeeViewInput,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getEmployee(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<EmployeeViewOutput>;
    getEmployee(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<EmployeeViewOutput>>;
    getEmployee(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<EmployeeViewOutput>>;
    getEmployee(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/employee/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    patchEmployee(id: string, employeeViewPatchInput: EmployeeViewPatchInput, observe?: 'body', options?: RequestOptions<'json'>): Observable<EmployeeViewOutput>;
    patchEmployee(id: string, employeeViewPatchInput: EmployeeViewPatchInput, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<EmployeeViewOutput>>;
    patchEmployee(id: string, employeeViewPatchInput: EmployeeViewPatchInput, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<EmployeeViewOutput>>;
    patchEmployee(id: string, employeeViewPatchInput: EmployeeViewPatchInput, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/employee/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: employeeViewPatchInput,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteEmployee(id: string, observe?: 'body', options?: RequestOptions<'text'>): Observable<string>;
    deleteEmployee(id: string, observe?: 'response', options?: RequestOptions<'text'>): Observable<HttpResponse<string>>;
    deleteEmployee(id: string, observe?: 'events', options?: RequestOptions<'text'>): Observable<HttpEvent<string>>;
    deleteEmployee(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/employee/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            responseType: 'text',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
