/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { AssignmentControllerService } from "./assignmentController.service";
export { EmployeeControllerService } from "./employeeController.service";
