/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for UserController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, UserViewOutput, UserViewInput, UserViewPatchInput } from "../models";

@Injectable({ providedIn: "root" })
export class UserControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAll(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<UserViewOutput>>;
    getAll(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<UserViewOutput>>>;
    getAll(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<UserViewOutput>>>;
    getAll(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/user`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createUser(userViewInput: UserViewInput, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserViewOutput>;
    createUser(userViewInput: UserViewInput, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserViewOutput>>;
    createUser(userViewInput: UserViewInput, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserViewOutput>>;
    createUser(userViewInput: UserViewInput, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/user`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: userViewInput,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getUser(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserViewOutput>;
    getUser(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserViewOutput>>;
    getUser(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserViewOutput>>;
    getUser(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/user/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    patchUser(id: string, userViewPatchInput: UserViewPatchInput, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserViewOutput>;
    patchUser(id: string, userViewPatchInput: UserViewPatchInput, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserViewOutput>>;
    patchUser(id: string, userViewPatchInput: UserViewPatchInput, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserViewOutput>>;
    patchUser(id: string, userViewPatchInput: UserViewPatchInput, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/user/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: userViewPatchInput,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteUser(id: string, observe?: 'body', options?: RequestOptions<'text'>): Observable<string>;
    deleteUser(id: string, observe?: 'response', options?: RequestOptions<'text'>): Observable<HttpResponse<string>>;
    deleteUser(id: string, observe?: 'events', options?: RequestOptions<'text'>): Observable<HttpEvent<string>>;
    deleteUser(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/user/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            responseType: 'text',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
