/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface EmployeeViewInput {
    name: string;
    email: string;
}

export interface EmployeeViewOutput {
    id?: string;
    name: string;
    email: string;
}

export interface Assignment {
    id?: string;
    startTime?: Date;
    endTime?: Date;
    employee?: Employee;
}

export interface AssignmentViewInput {
    startTime: Date;
    endTime: Date;
    employee: Employee;
}

export interface Employee {
    id?: string;
    name?: string;
    email?: string;
    assignments?: Array<Assignment>;
}

export interface AssignmentViewOutput {
    id: string;
    startTime: Date;
    endTime: Date;
    employee: Employee;
}

export interface EmployeeViewPatchInput {
    name: string;
    email: string;
}

export interface AssignmentViewPatchInput {
    id: string;
    startTime: Date;
    endTime: Date;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
